version: "3"
services:
  db:
    image: mysql:8.0.20
    platform: linux/amd64
    volumes:
      - mysql:/var/lib/mysql:delegated
    environment:
      MYSQL_ROOT_PASSWORD: password
      TZ: Asia/Tokyo
    ports:
      - '3307:3306'
    command: --default-authentication-plugin=mysql_native_password
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: /bin/sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    tty: true
    stdin_open: true
    depends_on:
      - db
      - chrome
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      - NODE_OPTIONS=--openssl-legacy-provider
      - SELENIUM_REMOTE_URL=http://chrome:4444/wd/hub
  chrome:
    image: selenium/standalone-chrome:latest
    ports:
      - 4444:4444

volumes:
  mysql:
