default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch('MYSQL_USERNAME') { 'root' } %>
  password: password
  host: 'db'
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: gardenscheduler_development
  username: root

test:
  <<: *default
  database: gardenscheduler_test

production:
  <<: *default
  database: gardenscheduler_production
  username: root
  password: <%= ENV['APP_DATABASE_PASSWORD'] %>
  host: localhost
  socket: /var/lib/mysql/mysql.sock
