name: RUN Rspec
on: [push]

jobs:
  rspec:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0.20
        ports:
          - "3306:3306"
        env:
          MYSQL_USER: root
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
        options: --health-cmd "mysqladmin ping" --health-interval 10s --health-timeout 5s --health-retries 10

    env:
      RAILS_ENV: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Ruby and install gems
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Set up yarn and node
        run: |
          curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
          echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list
          curl -sL https://deb.nodesource.com/setup_12.x | bash -
          apt install -y yarn nodejs

      - name: Install chrome
        run: |
          wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | apt-key add -
          echo 'deb http://dl.google.com/linux/chrome/deb/ stable main' | tee /etc/apt/sources.list.d/google-chrome.list
          apt update -y
          apt install -y google-chrome-stable

      - name: Install dependent libralies
        run: sudo apt-get install libmysqlclient-dev

      - name: bundle install
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3

      - name: yarn install
        run: yarn install --ignore-engines

      - name: Setup Database
        run: |
          cp config/database.yml.ci config/database.yml
          bundle exec rails db:create
          bundle exec rails db:migrate
        env:
          RAILS_ENV: test

      - name: run rspec
        run: bundle exec rspec
        env:
          RAILS_ENV: test

      # - name: Archive rspec result screenshots
      #   if: failure()
      #   uses: actions/upload-artifact@v1
      #   with:
      #     name: rspec result screenshots
      #     path: tmp/screenshots/
